FROM python:3.12-slim

LABEL maintainer="Bernd Doser <bernd.doser@h-its.org>"

# Install the python requirements
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY plot_on_demand.py ./

# Download the trained gaia model
ADD https://space.h-its.org/models/gaia-v1/encoder.onnx ./gaia-v1/
ADD https://space.h-its.org/models/gaia-v1/decoder.onnx ./gaia-v1/

EXPOSE 8080

CMD ["python", "./plot_on_demand.py"]