#!/usr/bin/env python3

from jsonargparse import auto_cli

from hipster import HTMLGenerator, Task


def main(
    html: HTMLGenerator = HTMLGenerator(),
    tasks: list[Task] = [],
    output_folder: str = "./HiPSter",
    project_name: str = "project",
    only_html: bool = False,
):
    """
    Main function to generate HiPS data.

    Args:
        html (HTMLGenerator): An instance of HTMLGenerator to create the HTML page.
        tasks (list[Task]): A list of tasks to perform.
        output_folder (str): The folder to save the generated HiPS data.
        project_name (str): The name of the project. Default is "project".
    """

    if not only_html:
        for task in tasks:
            task.output_folder = output_folder
            task.project_name = project_name
            task.execute()

    html.add_image_layer(
        html.ImageLayer(
            name=project_name,
            description="HiPS data generated by HiPSter",
            url=f"{html.url}/{project_name}",
            order=0,
        )
    )
    html.generate(output_folder, project_name)


def main_cli():
    """
    Command line interface for the main function.
    """
    auto_cli(main)


if __name__ == "__main__":
    main_cli()
